const AMENITY_ICON_MAP: Record<string, string> = {
  sunshine: 'fa-sun',
  haunted: 'fa-ghost',
  ac: 'fa-snowflake',
  heat: 'fa-fire',
  wifi: 'fa-wifi',
  kitchen: 'fa-utensils',
  fridge: 'fa-box-open',
  microwave: 'fa-microchip',
  cooking: 'fa-utensils',
  dishes: 'fa-utensils',
  dishwasher: 'fa-broom',
  stove: 'fa-fire',
  oven: 'fa-oven',
  keurig: 'fa-mug-hot',
  glasses: 'fa-wine-glass',
  table: 'fa-table',
  yard: 'fa-tree',
  fire: 'fa-fire',
  onsiteparking: 'fa-car',
  streetparking: 'fa-parking',
  selfcheckin: 'fa-key',
  keypad: 'fa-keyboard',
  cameras: 'fa-camera',
  smokealarm: 'fa-bell',
  coalarm: 'fa-bell',
  fireextinguisher: 'fa-fire-extinguisher',
  firstaid: 'fa-first-aid',
  linens: 'fa-bed',
  curtains: 'fa-curtain',
  hairdryer: 'fa-wind',
  hotwater: 'fa-hot-tub',
};

export default AMENITY_ICON_MAP;
