import React from 'react';
import {
  FaBed,
  FaWifi,
  FaUtensils,
  FaMugHot,
  FaParking,
  FaKey,
  FaCamera,
  FaFire,
  FaSnowflake,
  FaBath,
  FaTv,
  FaWrench,
  FaWineGlass,
  FaTable,
  FaCar,
  FaShieldAlt,
  FaSun,
  FaGhost,
  FaTree,
  FaKeyboard,
  FaBell,
  FaFireExtinguisher,
  FaFirstAid,
  FaHotTub,
  FaBoxOpen,
  FaBroom,
} from 'react-icons/fa';

export const ICONS = [
  { label: 'Bed', value: 'fa-bed', Icon: FaBed },
  { label: 'WiFi', value: 'fa-wifi', Icon: FaWifi },
  { label: 'Utensils', value: 'fa-utensils', Icon: FaUtensils },
  { label: 'Coffee', value: 'fa-mug-hot', Icon: FaMugHot },
  { label: 'Parking', value: 'fa-parking', Icon: FaParking },
  { label: 'Key', value: 'fa-key', Icon: FaKey },
  { label: 'Camera', value: 'fa-camera', Icon: FaCamera },
  { label: 'Fire', value: 'fa-fire', Icon: FaFire },
  { label: 'AC', value: 'fa-snowflake', Icon: FaSnowflake },
  { label: 'Bath', value: 'fa-bath', Icon: FaBath },
  { label: 'TV', value: 'fa-tv', Icon: FaTv },
  { label: 'Wrench', value: 'fa-wrench', Icon: FaWrench },
  { label: 'Wine glass', value: 'fa-wine-glass', Icon: FaWineGlass },
  { label: 'Table', value: 'fa-table', Icon: FaTable },
  { label: 'Car', value: 'fa-car', Icon: FaCar },
  { label: 'Shield', value: 'fa-shield-alt', Icon: FaShieldAlt },
  { label: 'Sun / Sunshine', value: 'fa-sun', Icon: FaSun },
  { label: 'Haunted / Ghost', value: 'fa-ghost', Icon: FaGhost },
  { label: 'Yard / Tree', value: 'fa-tree', Icon: FaTree },
  { label: 'Keyboard / Keypad', value: 'fa-keyboard', Icon: FaKeyboard },
  { label: 'Alarm / Bell', value: 'fa-bell', Icon: FaBell },
  { label: 'Fire Extinguisher', value: 'fa-fire-extinguisher', Icon: FaFireExtinguisher },
  { label: 'First Aid', value: 'fa-first-aid', Icon: FaFirstAid },
  { label: 'Hot water / Hot tub', value: 'fa-hot-tub', Icon: FaHotTub },
  { label: 'Fridge / Box', value: 'fa-box-open', Icon: FaBoxOpen },
  { label: 'Cleaning / Broom', value: 'fa-broom', Icon: FaBroom },
];

export default ICONS;
