import React from 'react';
import {
  FaBed,
  FaWifi,
  FaUtensils,
  FaMugHot,
  FaParking,
  FaKey,
  FaCamera,
  FaFire,
  FaSnowflake,
  FaBath,
  FaTv,
  FaWrench,
  FaWineGlass,
  FaTable,
  FaCar,
  FaShieldAlt,
  FaSun,
  FaGhost,
  FaTree,
  FaKeyboard,
  FaBell,
  FaFireExtinguisher,
  FaFirstAid,
  FaHotTub,
  FaBoxOpen,
  FaBroom,
  FaConciergeBell,
  FaCocktail,
  FaSwimmingPool,
  FaSwimmer,
  FaDumbbell,
  FaBicycle,
  FaShip,
  FaPlane,
  FaBus,
  FaTaxi,
  FaMapMarkerAlt,
  FaUmbrellaBeach,
  FaSuitcase,
  FaSuitcaseRolling,
  FaLeaf,
  FaGlassCheers,
  FaGlassMartiniAlt,
  FaGlassWhiskey,
  FaToilet,
  FaShower,
  FaCoffee,
} from 'react-icons/fa';
import {
  MdPool,
  MdLocalBar,
  MdFitnessCenter,
  MdLocalParking,
  MdLocalLaundryService,
  MdRestaurant,
  MdLocalCafe,
  MdHotel,
  MdRoomService,
} from 'react-icons/md';

export const ICONS = [
  { label: 'Bed', value: 'fa-bed', Icon: FaBed },
  { label: 'WiFi', value: 'fa-wifi', Icon: FaWifi },
  { label: 'Utensils', value: 'fa-utensils', Icon: FaUtensils },
  { label: 'Coffee', value: 'fa-mug-hot', Icon: FaMugHot },
  { label: 'Parking', value: 'fa-parking', Icon: FaParking },
  { label: 'Key', value: 'fa-key', Icon: FaKey },
  { label: 'Camera', value: 'fa-camera', Icon: FaCamera },
  { label: 'Fire', value: 'fa-fire', Icon: FaFire },
  { label: 'AC', value: 'fa-snowflake', Icon: FaSnowflake },
  { label: 'Bath', value: 'fa-bath', Icon: FaBath },
  { label: 'TV', value: 'fa-tv', Icon: FaTv },
  { label: 'Wrench', value: 'fa-wrench', Icon: FaWrench },
  { label: 'Wine glass', value: 'fa-wine-glass', Icon: FaWineGlass },
  { label: 'Table', value: 'fa-table', Icon: FaTable },
  { label: 'Car', value: 'fa-car', Icon: FaCar },
  { label: 'Shield', value: 'fa-shield-alt', Icon: FaShieldAlt },
  { label: 'Sun / Sunshine', value: 'fa-sun', Icon: FaSun },
  { label: 'Haunted / Ghost', value: 'fa-ghost', Icon: FaGhost },
  { label: 'Yard / Tree', value: 'fa-tree', Icon: FaTree },
  { label: 'Keyboard / Keypad', value: 'fa-keyboard', Icon: FaKeyboard },
  { label: 'Alarm / Bell', value: 'fa-bell', Icon: FaBell },
  { label: 'Fire Extinguisher', value: 'fa-fire-extinguisher', Icon: FaFireExtinguisher },
  { label: 'First Aid', value: 'fa-first-aid', Icon: FaFirstAid },
  { label: 'Hot water / Hot tub', value: 'fa-hot-tub', Icon: FaHotTub },
  { label: 'Fridge / Box', value: 'fa-box-open', Icon: FaBoxOpen },
  { label: 'Cleaning / Broom', value: 'fa-broom', Icon: FaBroom },
  { label: 'Concierge / Bell', value: 'fa-concierge-bell', Icon: FaConciergeBell },
  { label: 'Cocktail / Bar', value: 'fa-cocktail', Icon: FaCocktail },
  { label: 'Swimming Pool', value: 'fa-swimming-pool', Icon: FaSwimmingPool },
  { label: 'Swimmer', value: 'fa-swimmer', Icon: FaSwimmer },
  { label: 'Gym / Dumbbell', value: 'fa-dumbbell', Icon: FaDumbbell },
  { label: 'Bicycle', value: 'fa-bicycle', Icon: FaBicycle },
  { label: 'Boat / Ship', value: 'fa-ship', Icon: FaShip },
  { label: 'Plane / Flights', value: 'fa-plane', Icon: FaPlane },
  { label: 'Bus', value: 'fa-bus', Icon: FaBus },
  { label: 'Taxi', value: 'fa-taxi', Icon: FaTaxi },
  { label: 'Map marker', value: 'fa-map-marker-alt', Icon: FaMapMarkerAlt },
  { label: 'Beach / Umbrella', value: 'fa-umbrella-beach', Icon: FaUmbrellaBeach },
  { label: 'Luggage / Suitcase', value: 'fa-suitcase', Icon: FaSuitcase },
  { label: 'Rolling suitcase', value: 'fa-suitcase-rolling', Icon: FaSuitcaseRolling },
  { label: 'Garden / Leaf', value: 'fa-leaf', Icon: FaLeaf },
  { label: 'Cheers / Glass', value: 'fa-glass-cheers', Icon: FaGlassCheers },
  { label: 'Martini', value: 'fa-glass-martini-alt', Icon: FaGlassMartiniAlt },
  { label: 'Whiskey', value: 'fa-glass-whiskey', Icon: FaGlassWhiskey },
  { label: 'Shower', value: 'fa-shower', Icon: FaShower },
  { label: 'Toilet', value: 'fa-toilet', Icon: FaToilet },
  { label: 'Coffee (alt)', value: 'fa-coffee', Icon: FaCoffee },
  { label: 'Material: Pool', value: 'md-pool', Icon: MdPool },
  { label: 'Material: Bar', value: 'md-local-bar', Icon: MdLocalBar },
  { label: 'Material: Gym', value: 'md-fitness-center', Icon: MdFitnessCenter },
  { label: 'Material: Parking', value: 'md-local-parking', Icon: MdLocalParking },
  { label: 'Material: Laundry', value: 'md-local-laundry-service', Icon: MdLocalLaundryService },
  { label: 'Material: Restaurant', value: 'md-restaurant', Icon: MdRestaurant },
  { label: 'Material: Cafe', value: 'md-local-cafe', Icon: MdLocalCafe },
  { label: 'Material: Hotel', value: 'md-hotel', Icon: MdHotel },
  { label: 'Material: Room Service', value: 'md-room-service', Icon: MdRoomService },
];

export default ICONS;
